contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #apa channel"
    url: https://nfcore.slack.com/channels/apa
    about: Discussion about the nf-core/apa pipeline
